### ISSUE TITLE
fix docs plz

### ISSUE THREAD

**Issue by chppppp** [jaebradley/draftkings_client#14]
Following the readme i get this. You also might want to update the readme to show the correct package (draft_kings_client, not draftkings_client)

root@asdasdasd:/tmp# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from draft_kings_client import DraftKingsClient, Sport
>>> return DraftKingsClient.get_contests(league=League.nba)
  File "<stdin>", line 1
SyntaxError: 'return' outside function
>>> print DraftKingsClient.get_contests(league=League.nba)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'League' is not defined
>>>

**Comment by chppppp** [comment]
looks like the correct method is  DraftKingsClient.get_contests(sport=Sport.nba)
