### ISSUE TITLE
Error Trying to Run Examples

### ISSUE THREAD

**Issue by AccidentalGuru** [jaebradley/draftkings_client#32]
Hi, this looks like it could be really useful. I can't get the example code to run in IDLE.

Is there something that I am missing?

Thanks,

Daniel

>>> from draft_kings_client import DraftKingsClient
Traceback (most recent call last):
  File "<pyshell#41>", line 1, in <module>
    from draft_kings_client import DraftKingsClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/draft_kings_client/__init__.py", line 1, in <module>
    from draft_kings_client import DraftKingsClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/draft_kings_client/DraftKingsClient.py", line 3, in <module>
    from data.models.sport import Sport
ModuleNotFoundError: No module named 'data'

**Comment by jaebradley** [comment]
@AccidentalGuru thanks for reporting this issue - I'll look into this sometime later tonight or this weekend.

**Comment by jaebradley** [comment]
@AccidentalGuru you'll see I published a V2 which should hopefully resolve many of the issues you were running into
